version: 1.0
# 数据源
spring:
  #  servlet:
  #    multipart:
  #      max-file-size: 1000MB
  #      max-request-size: 1000MB
  #      location: /data/upload_tmp
  datasource:
    #    type: com.alibaba.druid.pool.DruidDataSource
    #    base:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/nbmh?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: root
    password: mcraJL@888
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    #连接超时时间
    timeout: 5000

logging:
  level:
    com.baomidou: debug
    com.hszn.nbmh: debug
    com.github.binarywang: debug